# docker compose version
version: '3.9'

# services for the different container
services:
  # database-service includes the postgres-db and the cronjob for backups
  database:
    # image out of dockerfile from docker/database
    image: "xtramarcf/asset_management:database"
    # env vars for db credentials
    environment:
      - 'POSTGRES_PASSWORD=CXtkhXw96xMQm8'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=assetmanagement'
    # mounted volume for backup
    volumes:
      - "C:/Users/mf.FREUND/Documents/:/var/backups/"
    container_name: database
  # backend-service with business logic
  backend:
    # spring application
    image: "xtramarcf/asset_management:backend"
    # first starts database, then backend
    depends_on:
      - database
    # env vars for db credentials and admin password
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/assetmanagement'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=CXtkhXw96xMQm8'
      - 'KEY_ADMIN-PASSWORD=password123456'
    ports:
      - "8080:8080"
    container_name: backend
  frontend:
    # angular frontend
    image: "xtramarcf/asset_management:frontend"
    # first starts backend, then database
    depends_on:
      - backend
    ports:
      - "4200:4200"
    container_name: frontend
